// art section data
const artData = [
  {
    idx: 1,
    title: "ABANG",
    desc: "Gispen 2205 Chair",
    bgColor: "#d34640",
    attr: "art1.html",
    image: "./img/art1.png",
    imageSize: "59.4 x 42cm",
    frameSize: "60 x 42.5cm (A2)",
    productionMethod: " Pigment print on paper",
    material: "Red aluminium frame, acrylic",
    imageDesc: "What stories do the chairs in Avang's paintings hold? The Chair Collection art poster series is a collaboration between Print Bakery and the artist Avang. Avang's Chair Collection series captures the essence of chairs, which convey comfort in everyday life, through the artist's perspective. The series, limited to only 100 copies, holds collectible value and is an excellent way to change the atmosphere of a room with a subtle shift. The chair, as a medium to enjoy one's imagination in ultimate comfort. I hope the warmth of objects, like the chair, will bring to mind each person’s own warm moments.-Avang, from the artist’s note -",
  },
  {
    idx: 2,
    title: "Min Suyeon",
    desc: "Vacation 1, 2023",
    attr: "art1.html",
    bgColor: "#5390ae",
    image: "./img/art2.png",
    imageSize: "45 x 30 cm",
    productionMethod: "Hand paintedHand painted",
    material: "Mixed materials on mirror",
    imageDesc: "Min Sooyeon visualizes an aphorism on the finiteness of time through the theme, Everything that brushes past me is sorrowful. By incorporating mirrors, she imbues still images with a sense of temporality, creating paintings that exist only in the present. Through this approach, her work reflects the passage of time rather than just isolated moments. Within the playful imagery lies a contemplation of human solitude and a reverence for nature.",
  },
  {
    idx: 3,
    title: "Yeye",
    desc: "Life in 4 Frames",
    attr: "art1.html",
    bgColor: "#1a9388",
    image: "./img/art3.png",
    imageSize: "Frame 42.2 x 59.7cm",
    productionMethod: "Pigment print on paper",
    material: "Black aluminium frame, acrylic",
    imageDesc: "Yeye is an illustrator who captures the countless indescribable emotions and the special, joyful moments of daily life shared with her companion dog, Munggae. She introduces a charming art poster filled with memories of Munggae, who was like a hero to her.My hope is that my drawings become a fragrance, a breeze, and a furry friend of the heart that walks alongside many. And that they serve as a bridge, reminding someone of a precious presence.",
  },
  {
    idx: 4,
    title: "David Shrigley",
    desc: "Be nice",
    attr: "art1.html",
    bgColor: "#e1a800",
    image: "./img/art4.png",
    imageSize: "W50 x H67cm",
    productionMethod: "15 colour screenprint on Somerset Tub Sized 410gsm paper",
    material: "Paper",
    imageDesc: "Spread kindness around your kitchen with this Be Nice tea towel. Featuring Shrigley’s adorable rainbow and the lovely phrase Be Nice, this tea towel effortlessly blends into your space, even when casually hung in a corner of the kitchen. Made from 100% linen, it offers excellent drying and breathability while also serving as a charming fabric poster.",
  },
  {
    idx: 5,
    title: "David Shrigley",
    desc: "Curious Foot",
    attr: "art1.html",
    bgColor: "#c09783",
    image: "./img/art5.png",
    imageSize: "W9cm x H24 x D11cm",
    material: "Ceramic",
    imageDesc: "David Shrigley’s curious foot egg stand. Designed by David Shrigley, this foot is the most magnificent foot in the world when placed on the dining table. Boil an egg and place it on this curious foot, bringing perfect stability to your breakfast. Add an astonishingly cool foot to your kitchen collection.",
  },
  {
    idx: 6,
    title: "Erwin Wurm",
    desc: "Shine",
    attr: "art1.html",
    bgColor: "#6dd8f4",
    image: "./img/art6.png",
    imageSize: "Image 100 x 80cm",
    productionMethod: "High rendered print on canvas, inner frame, dibond backplate",
    material: "canvas",
    imageDesc: "Erwin Wurm is a sculptor from Austria. Through the process of creating and deconstructing sculptures, he explores new approaches to sculptural forms, expanding dimensions, weight, and volume. Beginning with the initial encounter between a flat canvas and painting, his Flat Sculptures series has become an iconic body of work, capturing the attention of collectors worldwide.Using a high-rendered print technique, this piece flawlessly reproduces the texture, paint depth, brushstrokes, density, and atmosphere of the original artwork. It comes with a specially designed package for safe and distinctive storage, along with cotton gloves and a gallery certificate",
},
  {
    idx: 7,
    title: "Kyne",
    desc: "Untitled : N, 2021",
    attr: "art1.html",
    bgColor: "#847449",
    image: "./img/art7.png",
    imageSize: "Image 57x46cm",
    productionMethod: "Silkscreen",
    material: "Paper, White wood frame",
    imageDesc: "KINE is a graffiti artist based in Fukuoka, Japan. He operates the atelier and offline shop ON AIR, where he introduces his work to the public. Combining the flatness and graphic simplicity of Japanese ukiyo-e with the pop culture of the 1980s, he paints enigmatic, mystical-eyed boys and girls.Although he studied nihonga (traditional Japanese painting) at university, his exposure to graffiti, street culture, pop culture, and contemporary hybrid art led him to focus on monochromatic two-tone acrylic paintings after graduation. Through his artwork, he stylishly expresses the diverse influences that have shaped him, depicting women with cool, composed gazes that engage the viewer.Beyond painting, KINE actively collaborates on merchandise, music, and brand projects, gaining significant popularity among young collectors.",
  },
  {
    idx: 8,
    title: "David Shrigley",
    desc: "shit",
    attr: "art1.html",
    bgColor: "#86003e",
    image: "./img/art8.png",
    imageSize: "65 x 50 cm",
    productionMethod: "Silkscreen",
    material: "Paper",
    imageDesc: "Nominated for the Turner Prize in 2013, Glasgow School of Art alumnus Shrigley created an elongated thumbs-up for the Fourth Plinth in London's Trafalgar Square in 2016, possibly satirically, in the hope of making the world a better place, while his playful drawings, paintings, photographs, and sculptures are imbued with deadpan humor that encapsulates the bizarre nuances of modern life, never correcting his work so that the resulting scratches and crossings out only add to its appeal.",
  },
  {
    idx: 9,
    title: "Choi Yunjung",
    desc: "oneday 76, 2023",
    attr: "art1.html",
    bgColor: "#f6bc7c",
    image: "./img/art9.png",
    imageSize: "15.8 x 15.8cm",
    productionMethod: "Hand painted",
    material: "Oil on Canvas",
    imageDesc: "The Illusion painting series begins by capturing the fleeting, illusionary images of light and shadow found in my everyday spaces. One day, in a cold, rigid environment I pass through daily, I encounter the shimmering light and shadow of a tree, swaying gently in the breeze. When the phenomenon lingers in the space, I feel as if I am experiencing the place for the first time, new and mysterious, and I find myself staring vacantly at the scene. This warm experience brought comfort to the mundane, difficult days and made me realize the preciousness of each moment. Even in the ordinary, repetitive nature of daily life, there is no moment that is insignificant or unworthy of gratitude, just as we, too, glow and shimmer in every moment, like the sparkling lights around us. The cool, calm shadows in everyday or new spaces, the flickering light I discover while walking down a path at a different time, the ever-changing air and temperature, and the warm sensations and atmospheres all serve as the inspiration and driving force behind my work. Through the process of capturing these images in my art, I reflect the emotions and thoughts I experience in daily life, projecting the various colors and soft feelings of light, aiming for a calm and stable expression. I hope that viewers, through my work, can experience the warm comfort and lazy rest I felt. My new works began with the imagination of capturing light within my heart. As I fill the canvas with simple forms of light and the colors of the day's emotions, I soon feel my heart filling with bright light, gradually warming.",
  },
  {
    idx: 10,
    title: "David Gerstein",
    desc: "Dutch Bouquet",
    attr: "art1.html",
    bgColor: "#b00700",
    image: "./img/art10.png",
    imageSize: "W:77 x H:100cm",
    productionMethod: "Hand painted cutout steel",
    material: "Steel, 3 layer",
    imageDesc: "Goldstein captures familiar everyday scenes, creating works that seem to come alive by cutting steel, adding color, and layering it into compositions that fluidly blur the boundary between object and flatness, offering a sense of space through his unique approach that transcends the boundaries of painting and sculpture, while evoking emotional comfort with themes of joy and happiness, fitting his nickname The Happy Artist.",
  },
  {
    idx: 11,
    title: "Lee Wooyoun",
    desc: "Hi-five of butterfly, 2023",
    attr: "art1.html",
    bgColor: "#6798c7",
    image: "./img/art11.png",
    imageSize: "72.7x53cm",
    productionMethod: "Hand painted",
    material: "Oil bar and oil on canvas",
    imageDesc: "Lee Woo-yeon adds value to everyday life and records ordinary yet special moments in tune with her own rhythm. Starting with esquisse, a process of simplifying forms, she gradually narrows the distance between herself and objects. Through pure observation, she focuses on the essence of things by limiting lines and surfaces, building intimacy. On a rough canvas mixed with sand, she fills the work with the spontaneity of changing lines and surfaces, ultimately completing a slice of daily life. Just as the day passes with big and small accidental events, Lee Woo-yeon listens attentively to the presence of things through her process, gradually filling her new daily life.",
  },
  {
    idx: 12,
    title: "Haydonna",
    desc: "Duh",
    attr: "art1.html",
    bgColor: "#000000",
    image: "./img/art12.png",
    imageSize: "80.3 x 100cm",
    productionMethod: "Hand painted",
    material: "Acrylic and gouache on canvas",
    imageDesc: "Haidana creates lovable pets that spark cute imaginations. She captures and expresses moments spent with her pets, offering a feeling as if you're sharing those moments yourself. Her canvas works, with their noticeable size, make great focal points in a space. Experience the simple yet happy daily life with your beloved pets, and fall in love all over again!",
  },
  {
    idx: 13,
    title: "Min Suyeon",
    desc: "The Express Bus Terminal Station in May., 2022",
    attr: "art1.html",
    bgColor: "#6db1da",
    image: "./img/art13.png",
    imageSize: "20 x 120 cm",
    productionMethod: "Hand painted",
    material: "Mixed materials on mirror",
    imageDesc: "Min Sooyeon visualizes an aphorism on the finiteness of time through the theme, Everything that brushes past me is sorrowful. By incorporating mirrors, she imbues still images with a sense of temporality, creating paintings that exist only in the present. Through this approach, her work reflects the passage of time rather than just isolated moments. Within the playful imagery lies a contemplation of human solitude and a reverence for nature.",
  },
  {
    idx: 14,
    title: "Pulrim",
    desc: "Wild flower series, 2022",
    attr: "art1.html",
    bgColor: "#dc4819",
    image: "./img/art14.png",
    imageSize: "53 x 33.4 cm (10M)",
    productionMethod: "Hand painted",
    material: "Acrylic on canvas",
    imageDesc: "Starting with the Full Sea series, the artist focuses on individual entities rather than groups, discussing the natural structures within urban environments. The artificially processed patterns that come together to create a landscape that feels natural reflect our fragmented perception of nature within the city. The comfort derived from the cultivated nature may represent the learned sense of security that urban dwellers possess. By alternating between concrete images of cultivated nature and abstract patterns resembling grassy fields, the artist poses a question about the naturalness of urban nature. Each landscape from memory is recombined on a single canvas, creating a new garden that does not exist in reality. This process mirrors the recurring cultivation and reconstruction of nature in urban spaces. The reshaped landscapes blend into familiar settings that the audience can easily relate to. Through this work, there is a need to recognize and question the natural structures within the city that we encounter every day: Is this truly nature?",
  },
  {
    idx: 15,
    title: "Kim Tschangyeul",
    desc: " Droplet 3",
    attr: "art1.html",
    bgColor: "#83724c",
    image: "./img/art15.png",
    imageSize: "121.4x162.2cm / Frame 122.4x163.2cm",
    productionMethod: "Pigment printing",
    material: "Acrylic on canvas",
    imageDesc: "My droplet paintings are the result of the meeting between my life experiences and my sculptural experiences. - Kim Chang-hwal, From the Time Spent with My Brother. A master of the 'droplet paintings' that graced the modern Korean art scene, Kim Chang-yeol lived through the turbulent history of Korea from 1929 to 2021. For nearly half a century, he conveyed the world of fullness in emptiness (無) through his droplet paintings. This edition, with its harmonious composition filling the entire canvas and the stark contrast between the raw burlap and the droplets, evokes a sense of grandeur. Simply encountering the droplets brings an overwhelming feeling of fulfillment and transmits a deep, clear energy of purification.",
  },
  {
    idx: 16,
    title: "Greta Frieden",
    desc: "SAN FRANCISCO",
    attr: "art1.html",
    bgColor: "#0037cc",
    image: "./img/art16.png",
    imageSize: "Frame 59.4x42cm",
    productionMethod: "Pigment printing",
    material: "German Durix Premium Matte 233g",
    imageDesc: "There is an elderly couple, Greta and Frieden, who continue to cherish and love each other even as their hair turns gray. Through their unique and vibrant fashion sense, the artist conveys a story about aging. For the artist, aging means always seeking adventure and never losing one’s distinctiveness. Though all things eventually fade, this work captures moments of love in everyday life, like watering flowers, always dreaming of eternity.",
  },
  {
    idx: 17,
    title: "Woo Inyoung",
    desc: "Blooming-Everything, P2204, 2022",
    attr: "art1.html",
    bgColor: "#c0dd13",
    image: "./img/art17.png",
    imageSize: "Frame 33 x 43.5 cm",
    productionMethod: "Hand painted",
    material: "Mixed media on paper",
    imageDesc: "Woo In-young reinterprets objects and natural motifs captured from daily life with simple shapes and colors, focusing on the beauty of form by excluding unnecessary elements. She believes that the beauty of a shape is seen differently when viewed from a step back. Through vibrant colors and a reinterpretation of nature, she offers a fresh perspective.",
  },
  {
    idx: 18,
    title: "David Shrigley",
    desc: "Look at this",
    attr: "art1.html",
    bgColor: "#f5002f",
    image: "./img/art18.png",
    imageSize: "Ø 70 cm",
    productionMethod: "Fabric Print",
    material: "Cotton, Polyester, Nonslip pad",
    imageDesc: "LOOK AT THIS! This soft-textured, bright red floor mat draws attention wherever it is placed. Shrigley's black humor message and playful accent colors bring vitality to a dull space, and the non-slip treatment on the bottom ensures it can be securely fixed in any desired location.",
  },
  {
    idx: 19,
    title: "Lee Wooyoun",
    desc: "Cake, 2024",
    attr: "art1.html",
    bgColor: "#e07192",
    image: "./img/art19.png",
    imageSize: "14.8 x 21cm / Frame 23.8 x 30cm",
    productionMethod: "Hand painted",
    material: "Oil bar and oil pastel on paper",
    imageDesc: "Lee Woo-yeon, the artist, adds value to everyday life and records moments that are ordinary yet special, following her own rhythm. She begins by simplifying shapes through sketches (Esquisse) and gradually closes the distance between herself and the objects. Through a pure perspective, she observes and restricts lines and surfaces, focusing on the essence of the objects to form intimacy. On a rough canvas mixed with sand, she fills the work with chance occurrences created by the changing lines and surfaces, ultimately completing a moment of everyday life. Just like how a day passes through a series of big and small accidental events, Lee Woo-yeon listens attentively to the existence of objects through the process and continues to fill a new daily life.",
  },
  {
    idx: 20,
    title: "Yoo Youngkuk",
    desc: "Mountain 1973",
    attr: "art1.html",
    bgColor: "#013614",
    imageSize: "90 x 90 cm / Frame 91 x 91 cm",
    productionMethod: "Pigment printing, acrylic pressing",
    material: "Acrylic on canvas",
    imageDesc: "In Yoo Young-kyuk's works, basic formal elements such as dots, lines, planes, shapes, and colors serve as the main subjects. They interact with each other, sometimes in tension and competition, while maintaining a certain sense of balance, thereby emitting intense energy. His works, evoking the deep sea, majestic mountains, clear valleys, and red sun of his hometown, Uljin, do not simply capture the realistic appearance of nature. However, the abstracted forms in his works bring the essence of nature even closer. His artwork demonstrates the process of gradually abstracting elements of nature that one encounters daily, such as mountains, seas, trees, hills, valleys, and sunsets. Painting mountains, I feel that within them are winding paths, which seem to represent life itself, and hidden within the mountains of my paintings are various forms of life. - Yoo Young-kyuk (From the Atelier magazine, 36th issue, Interview with Yoo Young-kyuk, April 25, 1995)",
  },
  {
    idx: 21,
    title: "Kim Bohie",
    desc: "Towards",
    attr: "art1.html",
    bgColor: "#40b068",
    image: "45.7 x 70cm / Frame 49.7 x 74cm",
    productionMethod: "Giclee print and silkscreen",
    material: "Oil bar and oil pastel on paper",
    imageDesc: "Kim Bo-hee, a master of representational landscape painting, explores the contemporary expansion of Eastern painting through her own techniques, which have been refined through an in-depth analysis and immersion in both Eastern and Western traditional styles of painting. She delicately expresses the beauty and purity of nature observed in everyday life, such as plants, gardens, the sea, and surrounding landscapes, using color ink wash painting.",
  },
  {
    idx: 22,
    title: "Yoo Youngkuk",
    desc: "Four seasons",
    attr: "art1.html",
    bgColor: "#5f5472",
    image: "./img/art22.png",
    imageSize: "Image 73x91cm",
    productionMethod: "Pigment printing",
    material: "Acrylic on canvas",
    imageDesc: "The work *Four Seasons*, created towards the end of Yoo Young-kyuk’s career, incorporates basic formal elements along with curves reminiscent of eaves. This piece contrasts with the artist's later years, during which he suffered from various illnesses, reflecting a state of transcendence. The use of warmer and more comfortable colors stands out compared to his earlier works. The blue skies, mountains, and seas, seemingly filled with the colors of the four seasons, invite viewers to experience the brilliant world of light that encompasses his artistic universe.",
  },
  {
    idx: 23,
    title: "David Gerstein",
    desc: "QUEENS OF THE SKY",
    attr: "art1.html",
    bgColor: "#f0b3ce",
    image: "./img/art23.png",
    imageSize: "W:194 x H:104cm",
    productionMethod: "Mixed media",
    material: "canvas",
    imageDesc: "The birds move in perfect unison, creating mesmerizing patterns dancing across the sky. Effortlessly, they glide on outstretched wings, forming a composition of colors and patterns. The array of birds soaring together expresses an ethereal quality, the spirit of freedom and harmony. The rich colors, along with the graceful motions, connect the birds of the flock; they are truly the 'Queens of the Sky.'",
  },
  {
    idx: 24,
    title: "Moon Hyeongtae",
    desc: "Mask Dance",
    attr: "art1.html",
    bgColor: "#290200",
    image: "./img/art24.png",
    imageSize: "Image 27.3x34cm / Frame 29.3x36cm",
    productionMethod: "Pigment printing",
    material: "Acrylic on canvas",
    imageDesc: "Moon Hyeong-tae creates whimsical, colorful paintings that encapsulate the weight of life, crafting fairy tales for adults and offering comfort to many. In this piece, the cute tiger and smiling people seem to be enjoying a happy New Year, filling the viewer with a delightful energy that promises a year full of joy.",
  },
];

// vote section data
const voteData = [
  {
    artist: "Jean-Paul Agosti",
    name: "MEDITATIO",
    size: "Image 100x100(cm)",
    method: "Pigment printing",
    material: "Acrylic",
    edition: "Limited edition 99",
    explain:
      "The work of Jean-Paul Agosti begins with taking photographs, and then a portion of those photographs is enlarged and replaced with painting. The subjects of the photographs he captures are very consistent, including gardens, forests, and trees reflected in water. As the photograph is transformed into a painting, the colors and forms undergo changes according to the artist's subjective interpretation, forming a new world. (Excerpt from the artist introduction in the Lee Eungno Museum, Lee Yung-se & Jean-Paul Agosti joint exhibition)",
  },
  {
    artist: "Song Hyeongno",
    name: "Rabbit into the hole",
    size: "Image 45.3 x 33.2 x 2.5cm",
    method: "Pigment printing",
    material: "Acrylic",
    edition: "Limited edition 150",
    explain:
      "A cute rabbit peeks out and greets us over the vast green field hall. This rabbit, as if it were a character from Alice in Wonderland, stands like a magical guide, its ears perked up as if encouraging us to keep going, telling us that we are almost at our destination.The lovable characters in Song Hyung-no's works are always messengers of dreams and hopes, spreading warmth, comfort, and love to the public.",
  },
  {
    artist: "Andy Rementer",
    name: "New growth",
    size: "Image 53 x 44.2 cm / Frame 66.2 x 55.4 cm",
    method: "Pigment printing",
    material: "Print paper,Pine wood,Front acrylic",
    edition: "Limited edition 45",
    explain:
      "Andy Limenter, an artist who gained recognition in Korea through solo exhibitions and brand collaborations, is showcasing new paintings and limited editions for this exhibition. While Andy's early works had a strong illustrative feel with clean lines, shapes, and coloring, his more recent works have embraced a painterly approach, with the mysterious expressions of the characters now becoming a distinctive feature of his style. The use of bright colors and contrasting mysterious moods has led to praise, making Andy's works even more intriguing.",
  },
];

export { artData, voteData };
